### ISSUE TITLE
Fix pyfun one notebook

### ISSUE THREAD

**Issue by mwaugh0328** [nyusterndatabootcamp/notebooks#1]
- [x] Create an outline at the top of the notebook emphasizing key stuff we are doing. Could just copy and past stuff from the book.

- [x] Create a warmup to the Jupyter notebook/markdown.

- [x] Clear the cells for the exercises.

- [x] Look through the text and make sure it makes sense. If not, edit as deemed appropriate.

- [x]  At end notebook create a summary. Maybe use the stuff from python fundamentals two to do so.

- [x]  Swap out (in notebook) objects and methods with dictionaries. Mike will help on edingint this.

- [x]  Better separate sections, use "---" to delaminate new area. Make the titling a bit bigger.

**Comment by Tinghao724** [comment]
Reports:

Task 1  I make changes to reflect the updated contents of the notebook and make it cleaner
Task 2 It is a short and clear version from the book.
Task 3 in this issue, I think it would better to clear all the cells. In any cases, if you do not want this, you can just run it and the results will pop out.

Task 4 Made updates and changes.
Task 5 Borrow and edit something in the python fundamentals two. Add an additional part for error message summaries.
Task 6 & 7 Done.

Meanwhile, I found some format issues in the book. Do we want to clean that as well or you want me to fork the book in this organization and edit?

**Comment by mwaugh0328** [comment]
Thanks @Tinghao724 ,

I edited a couple of things in the python fundamentals one notebook. The key was is around the exercises, we font' have the code cells with the answers in them. So we just have them there and then in class we can say create a new code cell and attempt to answer it. For our sake, we may want to have a solution (and numbering system) to keep track of things.

Can you do the similar things with python_fundamenta_two

A couple of other things:

- [x] Run a spell check on the notebooks. 

- [x] Need to insert instructions as to how to download a jupyter notebook from github. 

- [x] Create discussion about error terms in python fundamentals one.

**Comment by mwaugh0328** [comment]
Also about the book, yah, can you fork it into a new repository (just called book)? 

I will edit that, but once you have it forked, can you create a list of stuff that you find so we can fix it?

**Comment by Tinghao724** [comment]
Book Issues

I have forked and uploaded the book materials from the previous repos. 

I will summarize the to do list in the book repo issues.

In addition, recently the website of the gitbook has been updated, so does the authorization process. However, I have already figured how to publish and can show you on Wednesday meeting. It is a little bit confusing at the beginning.

**Comment by Tinghao724** [comment]
Follow-ups:
1) I have finished the additional tasks from you. Nice suggestions. Thanks

2) Regarding the exercises, I am sorry I misunderstood you at first and I think it's a great idea but I am still thinking about the way we indexing the exercises. For example, it cannot be from 1,2,3... If we want to add an exercise in between, we would have to change all the indexing afterwards. We might need to have a discussion over this in the meeting

Thanks!

**Comment by Tinghao724** [comment]
Hi Mike,

I have finished the notebook 2 following the similar things in notebook 1, would you please check that leave comments that I can further work on? Thanks!

**Comment by mwaugh0328** [comment]
Things to work on. @mwaugh0328 tasks
- [x] Go through @Tinghao724 changes
- [x] Better distinguish data types vs data structures
- [ ] Emphasis on the benefits of functions and develop exercises that emphasize the use of functions as good programming practice.  
- [ ] Better motivate and connect list comprehension with loops and its purpose

**Comment by mwaugh0328** [comment]
This stuff seems all done, the last comment was more about py fun2
