### ISSUE TITLE
intro to pandas notebook

### ISSUE THREAD

**Issue by mwaugh0328** [nyusterndatabootcamp/notebooks#2]
Several things todo:

- [x] Same generic tasks in other notebooks
- [x]  In introducing pandas, talk about the two core objects, series and dataframe. Not much space needs to be dedicated to a series, but a connection with numpy array and how it connects with a dataframe is important.
- [x] After basic properites about dataframe, discuss the idea that its a spreadsheet with named rows and columns. How do you grab the columns, talk through that, grab multiple columns, change the name etc. Next, is about the rows. We talk about the index, how it is indexed, how we can change the index. Then how to grab elements/rows from the datafram by using `.loc` and `.iloc` Later excercises in computation on a dataframe practice this.
- [x] Understand and describe the axis what it means, how to use it, e.g. sum across rows, how?

**Comment by Tinghao724** [comment]
I have made thoroughly changes regarding the notebook. I will continue check and update it when I am working on numpy. It'd be helpful that you could give some comments for guidance.  

comments:

task 1 & 2. Done
task 3. I just got a little bit confused about why using a two-step methods with loc to grab row data. Multiple indexing might be a little bit bit challenging, even though it is natural. Maybe a good stepping stone for group by methods in the future. I am not sure.
task4. I did not give it a specific section to it. However, I repeated 3 times in the notebook and used with different methods and compare the results while setting axis=1 and axis=0. 

Let me know if you have any additional idea.
